services:
  mediaharvest:
    build: .
    container_name: mediaharvest
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      PORT: 3000
      DOWNLOAD_DIR: /downloads
      MAX_CONCURRENT_DOWNLOADS: 2
    ports:
      - "3000:3000"
    volumes:
      - ./downloads:/downloads
